### ISSUE TITLE
反向shell中有一句话不通顺

### ISSUE THREAD

**Issue by ghost** [smartFlash/pySecurity#1]
“我非常的喜欢subprocess模块因为它允许你能储存STDOUT给一个变量”
“这个端口经常用在传输ssl的数据可以很容易的混淆数据”

翻译得不通顺的地方太多了....我还是看原文吧...

**Comment by ty4z2008** [comment]
看原文是最好的。但如果愿意一起维护是一件很开心的事情。

**Comment by ghost** [comment]
好多地方感觉太注重原文的语句而忽略了可读性，润色一下就好~

**Comment by ty4z2008** [comment]
嗯，谢谢你的建议。有时太忙并没有什么时间。我会一点一点的修正。同时也希望能邀请你加入进来一起修正
